version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: my-mongo
    restart: always
    ports:
      - '27017:27017'
  spring:
    image: buravil/spring-prometheus:0.0.1
    container_name: spring-actuator
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - spring
    restart: always

  grafana:
    image: grafana/grafana:6.4.5
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
    links:
      - prometheus
    depends_on:
      - prometheus
