version: '3.7'

services:

  mongo:
    image: mongo:3.6
    restart: always
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db

  spring-prometheus:
    image: buravil/spring-prometheus:0.0.1
    container_name: springprometheus
    links:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    depends_on:
      - mongo
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - "9090:9090"
    depends_on:
      - spring-prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
    links:
      - prometheus
    depends_on:
      - prometheus
