spring.application.name: demoservice
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


spring:
  data:
    mongodb:
      host: mongodb
logging.level.org:
  springframework:
    data:
      mongodb:
        core:
          MongoTemplate: DEBUG
